on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Generate README.md
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: node generate-readme.mjs

      - name: Update README.md
        run: |
          set -e
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README"
            git push
          fi
